### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/TetGen.jl#1]
It seems like TetGen is AGPL3: https://github.com/JuliaGeometry/TetGen.jl/blob/master/deps/tetgen1.5.1-beta1/LICENSE

Does this mean the wrapping has to be AGPL3 as well?

**Comment by SimonDanisch** [comment]
Common sense tells me, that what is licensed MIT is the wrapper code itself, while TetGen has its own licence... Or do you rather inherit the most constricted license used in your project?

**Comment by skariel** [comment]
This is how its done for NLopt: https://github.com/JuliaOpt/NLopt.jl/blob/master/LICENSE.md

**Comment by Kevin-Mattheus-Moerman** [comment]
Simon and I made the wrapper AGPL3 as well, since we envisioned that the source of TetGen may be included in the future.
