### ISSUE TITLE
Example does´t work in Julia 1.1.1

### ISSUE THREAD

**Issue by JMmontilla** [JuliaGeometry/TetGen.jl#10]
I´m trying to use the example to learn hot to use this wrapper but I get an error with the JLPolygon function saying that it doesn´t exist (is not defined). I run this:

```julia
using TetGen

points = zeros(8 * 3)
points[[4, 7, 8, 11]]  .= 2;  # node 2.
# Set node 5, 6, 7, 8.
for i in 4:7
  points[i * 3 + 1] = points[(i - 4) * 3 + 1];
  points[i * 3 + 1 + 1] = points[(i - 4) * 3 + 1 + 1];
  points[i * 3 + 2 + 1] = 12;
end

JLPolygon(Cint[1:4;])
```
And I get:

```julia
ERROR: UndefVarError: JLPolygon not defined
Stacktrace:
 [1] top-level scope at none:0
```
I´m working in Arch Linux Julia downloaded directly from the webpage.

**Comment by SimonDanisch** [comment]
You need to import those! Should probably add this in the example!

**Comment by JMmontilla** [comment]
Thanks!

But if I do:

```julia
using TetGen: JLPolygon
```
Then `JLPolygon(Cint[1:4;]) `gives me this error:

```julia
ERROR: MethodError: no method matching JLPolygon(::Array{Int32,1})
Closest candidates are:
  JLPolygon(::TetGen.CPolygon) at /home/astror/.julia/packages/TetGen/NvEhM/src/cppwrapper.jl:34
Stacktrace:
 [1] top-level scope at none:0
```

Not sure what it means. I suppose that it has something to do with the conversion to Integers in C format?

**Comment by SimonDanisch** [comment]
Hm not sure.. You should probably take an example from the tests - as far as I can tell they're passing, so that should work: https://github.com/JuliaGeometry/TetGen.jl/blob/master/test/runtests.jl

**Comment by JMmontilla** [comment]
Those test work fine, I think that they will do for what I want. Thank you very much :)
