### ISSUE TITLE
How to specify holes?

### ISSUE THREAD

**Issue by chakravala** [JuliaGeometry/TetGen.jl#17]
What's the syntax for specifying holes?

**Comment by SimonDanisch** [comment]
You'll need to construct a `TetgenIO` object directly and supply a hole list: https://github.com/JuliaGeometry/TetGen.jl/blob/master/src/cppwrapper.jl#L198
You can then call https://github.com/JuliaGeometry/TetGen.jl/blob/master/src/cppwrapper.jl#L390 directly... May need to look up the correct command, or reuse the ones used for the other commands: https://github.com/JuliaGeometry/TetGen.jl/blob/master/src/api.jl#L1

**Comment by chakravala** [comment]
Is `GeometryBasics.Mesh` going to be able to support holes? That would make it a more useful interface probably.

**Comment by SimonDanisch** [comment]
You could pass it as meta data and pick that up in the TetGen much like:
https://github.com/JuliaGeometry/TetGen.jl/blob/master/src/api.jl#L13

**Comment by chakravala** [comment]
Let's say I have a triangle mesh of the surface of a sphere, and I want to make it the hole in a cube tetrahedral mesh.

This means I will need to input both rectangular faces and triangular faces for `TetGen`, does `TetgenIO` support that?

**Comment by chakravala** [comment]
Alright, so I got a mesh with a spherical hole in it by triangulating the quad faces also, and then feeding all the faces into the mesh generation as `TriangleFaces` instead, and specifying the hole. That seems to work.

Let me know if there is supposed to be a way to combine both `QuadFace` and `TriangleFace` inputs.

**Comment by chakravala** [comment]
Issue closed with #18
