### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGeometry/TetGen.jl#2]
Any ideas on how to conveniently get Windows binaries?
I guess on unix compiling should be pretty straight forward.

**Comment by skariel** [comment]
I have dual boot Linux/Windows so maybe I'll be able to compile, I'll try later today

**Comment by skariel** [comment]
Windows binaries are here: https://github.com/JuliaGeometry/tetgen.dependency
Linux ones still missing :) I suggest we keep all original tetgen content in the tetgen.dependency repo under the AGPL license and develop this wrapper under the MIT license

**Comment by SimonDanisch** [comment]
Sounds like a good idea!
But don't we need a shared library to make things work nicely, or am I
missing something?

2015-02-10 21:46 GMT+01:00 Ariel Keselman <notifications@github.com>:

**Comment by SimonDanisch** [comment]
I actually generated a shared library for the predicates with MinGW (I didn't get CL to create Julia compatible DLL's), but I didn't know how to link this to tetgen. It gave me undefined symbols, which where most likely the predicates.
It should be quite easy, if you know g++/gcc a little better than me ;)

**Comment by skariel** [comment]
I just added the DLLs generated with VS, can you try them?

**Comment by SimonDanisch** [comment]
Totally forgot how annoying this whole C++ VS business is -.-
We don't really need a DLL right? Either we need to write a C-wrapper, or use Cxx, which both would just need the .lib, correct?
Your lib actually didn't work for me and I had to compile it myself (when linking it in a C++ test project). 
Did you define `#define TETLIBRARY` ?
Also, the dll is empty in dependency walker, which might not be a surprise because we would need to export the symbols?!
Sorry, has been a long time since I've worked with C++ ;)

**Comment by skariel** [comment]
I actually tired, doesn't work, Julia just cannot see the exported functions. I'll try again tomorrow

**Comment by skariel** [comment]
Yep well need to make a C-wrapper I guess, we need also to export the symbols. This is what I just did but still didn't work

**Comment by RaulDurand** [comment]
Any news on this matter?

**Comment by SimonDanisch** [comment]
Yes, this works now!
