### ISSUE TITLE
example code does not run

### ISSUE THREAD

**Issue by eahenle** [JuliaGeometry/TetGen.jl#26]
On both Julia 1.5.2 (Windows 10) and Julia 1.5.3 (Ubuntu 20), the example code given in the readme does not execute successfully.  First, `using TetGen: TetgenIO` gives `UndefVarError: TetGenIO not defined`.  Second, the call to `Mesh` does not run.  On Windows, the REPL crashes with no error message; on Linux, the REPL hangs indefinitely with the message "double free or corruption (!prev)"  Removing the maximum tetrahedron volume constraint allows the line to run.

**Comment by jlchan** [comment]
On Mac with Julia 1.6.2, removing the `using TetGen: TetgenIO` line seems to make the example work. I'm not sure about the `Mesh` error.

**Comment by j-fu** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/pull/3611 - once this gets merged, together with #27 this should work again.
