### ISSUE TITLE
libtet undefined 

### ISSUE THREAD

**Issue by iojea** [JuliaGeometry/TetGen.jl#28]
Hi, 
I am running Julia v1.7-rc arm64 on a MacBook Air with M1 chip. 
`]add TetGen`
works fine and TetGen seems to be installed without warnings. However,  when I try to run an example (any example), I get the following error:
`ERROR: UndefVarError: libtet not defined
Stacktrace:
 [1] tetrahedralize(input::RawTetGenIO{Float64}, flags::String)
   @ TetGen ~/.julia/packages/TetGen/pHPIP/src/rawtetgenio.jl:629`

I assume that libtet should had been created by the installation of TetGen.jl, but I could not find the file.  I can compile the original C++ version of TetGen as a library (thus, obtaining libtet.a), but I don't know how to make it accessible for TetGen.jl. 
Any ideas what the problem may be?
Thanks in advance. 
IO.

**Comment by j-fu** [comment]
For the Julia binary builder, macos aarch64  still seems to count as an experimental platform, see https://github.com/JuliaPackaging/Yggdrasil/issues/2763

So  libtet is not available yet for this architecturee, see the list on    https://github.com/JuliaBinaryWrappers/TetGen_jll.jl . 

However I don't expect any portability issues, so I will try to upgrade the binary package (also then for Triangle_jll.jl...) .
Need to carve out some time for this.

**Comment by j-fu** [comment]
This has been merged now - with TetGen_jll.jl 1.5.2 you could try  if it works...

**Comment by iojea** [comment]
It works perfectly fine. 
Thank you very much for the quick solution!
