### ISSUE TITLE
Enable handing of multi-region meshes and meshes containing holes

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaGeometry/TetGen.jl#4]
This requires proper handling of the: boundary marker, hole point, and region point attributes.

**Comment by Kevin-Mattheus-Moerman** [comment]
For a MATLAB wrapper see the [GIBBON](https://github.com/gibbonCode/GIBBON) project and the file:
https://github.com/gibbonCode/GIBBON/blob/master/docs/HELP_runTetGen.m

**Comment by SimonDanisch** [comment]
This should work now :) We should add some docs though!
