### ISSUE TITLE
Expand wrapper functionality to constrained 3D Delaunay/Voronoi tesselation

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaGeometry/TetGen.jl#5]

**Comment by Kevin-Mattheus-Moerman** [comment]
For a MATLAB implementation of constrained Delaunay tesselation with TetGen see: 
https://github.com/gibbonCode/GIBBON/blob/master/docs/HELP_constrainedDelaunayTetGen.m

**Comment by SimonDanisch** [comment]
Should work now, needs docs!
