### ISSUE TITLE
Add support for spatially varying density meshing

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaGeometry/TetGen.jl#6]
Allow users to specify a mesh sizing function (which is converted to a mtr file) enabling TetGen based spatially varying mesh generation. 

In MATLAB this has been done here:
https://github.com/gibbonCode/GIBBON/blob/master/docs/DEMO_tetGen_mesh_sizing_function_1.m

**Comment by SimonDanisch** [comment]
Should work - needs docs!
